spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: movie-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/cinema_movie_service_db?createDatabaseIfNotExist=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true

server:
  port: ${API_PORT}
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_ADDRESS}/eureka
