version: "3.1"

services:
  db:
    container_name: postgres_cinema_available_unit_service
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: available_unit_service_db
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGDATA: /data/postgres 
    ports:
      - "${PGPORT}:5432"
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: