server:
  port: 8761

spring:
  config:
    import: optional:file:.env[.properties]

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  username: ${EUREKA_USER}
  password: ${EUREKA_PASSWORD}
