version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    container_name: cinema_keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - ${KEYCLOAK_PORT}:8080
    networks:
      - keycloak_network
    command: ["start-dev"]
networks:
  keycloak_network:
    driver: bridge