spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/api/movies/*
        - id: available-units-service
          uri: lb://available-units-service/
          predicates:
            - Path=/api/available-units/*
        - id: discovery-service
          uri: ${DISCOVERY_SERVICE_ADDRESS}
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-service-static
          uri: ${DISCOVERY_SERVICE_ADDRESS}
          predicates:
            - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_HOST}/realms/cinema-microservices-realm
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_ADDRESS}/eureka

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route: 
              RouterDefinitionLocator: INFO 

